import type { AppMessages } from './types'

const passwordChecklist = {
	minLength: 'At least 8 characters',
	complexity: 'At least 3 criteria from the list below',
	lowercase: 'Lowercase letters',
	uppercase: 'Uppercase letters',
	number: 'Numbers',
	symbol: 'Symbols',
} as const

const en: AppMessages = {
	app: {
		name: 'Vitraux',
		helloWorld: 'Hello World',
		close: 'Close',
	},
	nav: {
		home: 'Home',
		images: 'Images',
		create: 'Create',
		settings: 'Settings',
		openMenu: 'Open menu',
		closeMenu: 'Close menu',
		menu: 'Menu',
		account: 'Account',
		signIn: 'Sign in',
		signUp: 'Sign up',
		profile: 'Profile',
		signOut: 'Sign out',
		mainNavigation: 'Main navigation',
	},
	validation: {
		required: 'This field is required',
		emailInvalid: 'Enter a valid email',
		emailRequired: 'Enter your email',
		passwordRequired: 'Enter your password',
		nicknameRequired: 'Enter your nickname',
		nicknameInvalid: 'Invalid nickname after normalization',
		identifierRequired: 'Enter your nickname or email',
		urlInvalid: 'Enter a valid URL',
		passwordConfirmationRequired: 'Confirm your password',
		currentPasswordRequired: 'Enter your current password',
		newPasswordRequired: 'Enter your new password',
		birthDateRequired: 'Enter your date of birth',
	},
	auth: {
		loginTitle: 'Sign in',
		registerTitle: 'Sign up',
		email: 'Email',
		identifier: 'Nickname or email',
		password: 'Password',
		passwordConfirmation: 'Confirm password',
		nickname: 'Nickname',
		birthDate: 'Date of birth',
		birthDateHint: 'You must be 18 years or older.',
		mustBeAdult: 'You must be at least 18 years old to create an account.',
		invalidBirthDate: 'Enter a valid date of birth.',
		submitLogin: 'Sign in',
		submitRegister: 'Create account',
		successLogin: 'Signed in successfully',
		successRegister: 'Account created successfully',
		errorGeneric: 'Could not complete the operation',
		invalidCredentials: 'Invalid nickname/email or password',
		nicknameTaken: 'Nickname already in use',
		nicknameAvailable: 'Nickname available',
		nicknameUniquenessHint:
			'Nicknames are unique, ignoring letter case. Lookalike characters from other alphabets are not allowed.',
		emailTaken: 'Email already in use',
		passwordMismatch: 'Passwords do not match',
		passwordMinLength: 'Password must be at least 8 characters',
		passwordComplexity: 'Password must meet at least 3 criteria from the list',
		showPassword: 'Show password',
		hidePassword: 'Hide password',
		passwordChecklist,
		noAccount: "Don't have an account?",
		registerNow: 'Register',
		acceptTerms: 'I have read and accept the <terms>Terms of Use</terms>.',
		acceptPrivacy: 'I have read and accept the <privacy>Privacy Policy</privacy>.',
		consentRequired: 'Accept the terms and the privacy policy to continue.',
		forgotPasswordLink: 'Forgot password?',
		forgotPasswordTitle: 'Forgot password',
		forgotPasswordHint: 'Enter your email. If an account exists and is verified, we will send a reset code.',
		forgotPasswordSubmit: 'Send reset code',
		forgotPasswordSuccess: 'If an account with that email exists and is verified, a reset code has been sent.',
		resetPasswordTitle: 'Reset password',
		resetPasswordSubmit: 'Update password',
		resetPasswordSuccess: 'Password updated. You can sign in with your new password.',
		resetPasswordError: 'Invalid or expired code. Request a new reset email.',
		resetCode: 'Reset code',
		newPassword: 'New password',
		newPasswordConfirmation: 'Confirm new password',
		backToLogin: 'Back to sign in',
		continueWithGoogle: 'Continue with Google',
		googleLoginRequired: 'This account uses Google. Sign in with Continue with Google.',
		googleRegisterTitle: 'Finish Google sign-up',
		googleRegisterHint: 'Confirm your age and accept the legal documents to create your account.',
		googleRegisterSubmit: 'Create account with Google',
		googleRegisterSuccess: 'Account created with Google',
		googleLinkTitle: 'Link Google account',
		googleLinkMessage:
			'A Vitraux account already exists with this email and a password. Enter your current password to link Google.',
		googleLinkSubmit: 'Link and sign in',
		googleLinkSuccess: 'Google linked successfully',
		emailChangeCancelledMessage: 'Continuing with Google cancels any pending email change on this account.',
		googleEmailUnverifiedMessage:
			'Your Google account email is not verified. You will need to verify your email again on Vitraux.',
	},
	legal: {
		privacyTitle: 'Privacy Policy',
		termsTitle: 'Terms of Use',
		privacyMetaDescription:
			'Vitraux privacy policy covering purposes, legal bases, retention, international transfers, and LGPD rights.',
		termsMetaDescription:
			'Vitraux terms of use covering accounts, uploaded content, platform rules, and cooperation with authorities.',
		versionLabel: 'Version {version}',
		privacyLink: 'Privacy',
		termsLink: 'Terms',
		privacyLinkShort: 'Privacy',
		termsLinkShort: 'Terms',
		linksLabel: 'Legal documents',
		cookieNotice:
			'We use essential cookies for session, theme, and language. We do not use marketing trackers. See the privacy policy for details.',
		cookieDismiss: 'Got it',
	},
	profile: {
		title: 'Profile',
		name: 'Full name',
		nickname: 'Nickname',
		nicknameUniquenessHint:
			'Nicknames are unique, ignoring letter case. Lookalike characters from other alphabets are not allowed.',
		photo: 'Profile photo',
		photoHelper: 'JPEG, PNG, WebP or GIF up to 3MB',
		addPhoto: 'Add profile photo',
		removePhoto: 'Remove profile photo',
		changePhoto: 'Click to change',
		saveProfile: 'Save profile',
		changePassword: 'Change password',
		currentPassword: 'Current password',
		currentPasswordGoogleHint:
			'Google accounts without a password can leave this field blank when setting the first password.',
		newPassword: 'New password',
		newPasswordConfirmation: 'Confirm new password',
		successProfile: 'Profile updated',
		successPassword: 'Password updated',
		successPhoto: 'Photo updated',
		downloadMyData: 'Download my data',
		successExport: 'Export ready',
		deleteAccount: 'Delete account',
		deleteAccountDescription:
			'Your account enters a 30-day quarantine. Content is hidden immediately. If you sign in within that period, you can cancel deletion. After 30 days, data is permanently erased.',
		deleteAccountConfirm: 'Type DELETE to confirm',
		deleteAccountPassword: 'Current password to confirm deletion',
		deleteAccountSubmit: 'Delete my account',
		successDeleteAccount: 'Deletion requested — account in quarantine',
		errorDeleteAccount: 'Could not delete the account',
		accountDeletion: {
			title: 'Account deletion requested',
			requestedAt: 'Request made on {datetime} (UTC) by you.',
			deadlineAt: 'Deadline to cancel and recover the account: {datetime} (UTC).',
			bodyQuarantine:
				'Your account and content are in quarantine and hidden. They can be restored if you cancel deletion within 30 days.',
			bodyRestore:
				'When you sign in to this account, you can CANCEL the deletion request (restore) or KEEP deletion (stay in quarantine).',
			bodyIrreversible: 'Under the LGPD, after the deadline your data will be deleted IRREVERSIBLY.',
			keepButton: 'KEEP profile deletion',
			cancelButton: 'CANCEL profile deletion',
			infoOnlyHint: 'We sent an email with these details. To cancel deletion, sign in again within the deadline.',
			successCancel: 'Deletion cancelled — account restored',
			successKeep: 'Deletion kept — account remains in quarantine',
			errorAction: 'Could not complete the action',
			loading: 'Loading…',
		},
		errorGeneric: 'Could not save changes',
		passwordMismatch: 'Passwords do not match',
		passwordMinLength: 'Password must be at least 8 characters',
		passwordComplexity: 'Password must meet at least 3 criteria from the list',
		showPassword: 'Show password',
		hidePassword: 'Hide password',
		passwordChecklist,
		accountUnverified: 'Account not verified',
		accountVerified: 'Account verified',
		email: 'Email',
		emailDisplay: 'Email: {email}',
		resendVerification: 'Resend verification email',
		verificationToken: 'Verification code',
		confirmVerification: 'Verify account',
		pendingEmailChange: 'Pending change to {email}',
		changeEmail: 'Change email',
		currentEmail: 'Current email',
		newEmail: 'New email',
		emailChangeInboxHint: 'Check your inbox to confirm the email change.',
		emailChangeRequiresVerified: 'Verify your account before changing email.',
		emailChangeUnlinksGoogleWarning:
			'Changing your email unlinks Google from this account. You will need to link it again later if you want.',
		emailChangeWillUnlinkGoogle: 'Google will be unlinked when the email change is completed.',
		successVerificationSent: 'Verification email sent',
		errorVerificationSent: 'Could not send the verification email',
		successEmailChangeRequested: 'Confirmation email sent to your current address',
		verifyEmailTitle: 'Verify email',
		verifyEmailSuccess: 'Your email was verified successfully.',
		verifyEmailError: 'Could not verify this email code.',
		confirmEmailChangeTitle: 'Confirm email change',
		confirmEmailChangeSuccess: 'Your email was updated successfully.',
		confirmEmailChangePendingNew: 'Current address confirmed. Check your new inbox to finish.',
		confirmEmailChangeError: 'Could not confirm this email change link.',
		goToProfile: 'Go to profile',
		activeSessions: 'Active sessions',
		sessionCurrent: 'This session',
		sessionRevoke: 'Revoke',
		sessionRevokeOthers: 'Revoke other sessions',
		sessionEmpty: 'No active sessions.',
		sessionDevice: 'Device',
		sessionCreated: 'Created',
		sessionExpires: 'Expires',
		statistics: 'Statistics',
		statisticsImageCount: 'Number of images',
		statisticsStorageUsed: 'Storage used',
		statisticsStorageUsedValue: '{megabytes} MB',
	},
	settings: {
		title: 'Settings',
		general: {
			title: 'General',
			description: 'Basic interface preferences.',
			darkMode: 'Enable dark mode',
			language: 'Language',
			showSecretImages: 'Show SECRET images',
			showSecretImagesDescription: 'Shows your SECRET images in My images and lets you mark images as SECRET.',
			appearInGlobalMosaic: 'Appear on the global mosaic',
			appearInGlobalMosaicDescription: 'If off, your public images stay out of the home feed.',
		},
		languages: {
			pt: 'Portuguese',
			en: 'English',
			es: 'Spanish',
		},
	},
	notFound: {
		title: 'Page not found',
		description: 'The requested address does not exist or is unavailable.',
		backHome: 'Back to home',
	},
	error: {
		title: 'Something went wrong',
		description: 'This page could not be loaded. Try again or go back to home.',
		retry: 'Try again',
		backHome: 'Back to home',
	},
	apiError: {
		timeout: 'The request took too long. Check your connection and try again.',
		unauthorized: 'Your session expired or you do not have permission. Sign in again.',
		server: 'The server ran into a problem. Try again in a moment.',
		network: 'Could not connect. Check your internet and try again.',
		generic: 'Could not complete the operation.',
	},
	mosaic: {
		close: 'Close',
		closeWithoutSaving: 'Close without saving',
		delete: 'Delete',
		deleteConfirm: 'Click again to delete',
		deleting: 'Deleting…',
		deleteError: 'Could not delete the image',
		deleteSuccess: 'Image deleted',
		save: 'Save',
		saving: 'Saving…',
		saveError: 'Could not save the image',
		saveSuccess: 'Image saved',
		isPrivate: 'Private',
		isSecret: 'Secret',
		showText: 'Show text',
		showImage: 'Show image',
		zoomLabel: 'Board zoom',
		zoomColumns: '{count} columns',
		imageMissing: 'This image does not exist or was deleted',
		untitled: 'Image',
		imageDetails: 'Image details',
		openImage: 'Open image',
		empty: 'No images yet.',
		loadMore: 'Load more',
	},
	report: {
		button: 'Report',
		title: 'Report image',
		description: 'Describe the issue. Our team will review the report.',
		reason: 'Reason',
		reasonPlaceholder: 'Select a reason',
		details: 'Details (optional)',
		detailsHint: 'Do not include unnecessary sensitive data.',
		submit: 'Submit report',
		cancel: 'Cancel',
		success: 'Report submitted',
		errorGeneric: 'Could not submit the report',
		alreadyReported: 'You already reported this image',
		loginRequired: 'Sign in to report',
		reasons: {
			spam: 'Spam',
			nudes_nonconsensual: 'Non-consensual nudes',
			csam: 'Child sexual abuse material (CSAM)',
			impersonation: 'Impersonation',
			other: 'Other',
		},
	},
	home: {
		searchLabel: 'Search images',
		searchPlaceholder: 'Search by title or description',
		noTagsYet: 'No tags yet',
		empty: 'No images published yet.',
		emptyFiltered: 'No images match these search criteria',
		loading: 'Loading…',
		loadError: 'Could not load images',
		loadMore: 'Load more',
	},
	documentTitle: {
		images: 'My images',
		create: 'New image',
		profile: 'My profile',
		settings: 'Settings',
		imageUpload: 'New image',
		imageMassUpload: 'Bulk upload',
		imageImportUrl: 'Import URL',
		imageImportPinterest: 'Import from Pinterest',
		privacy: 'Privacy',
		terms: 'Terms',
	},
	images: {
		pageTitle: 'My images',
		searchLabel: 'Search images',
		searchPlaceholder: 'Search by title or description',
		noTagsYet: 'No tags yet',
		empty: 'You have not uploaded any images yet.',
		emptyFiltered: 'No images match these search criteria',
		loading: 'Loading…',
		loadError: 'Could not load images',
		loadMore: 'Load more',
		createFab: 'Upload image',
		createTitle: 'New image',
		fileLabel: 'File',
		fileHint: 'JPEG, PNG, WebP or GIF up to 3MB',
		fileReadError: 'Could not read the file',
		titleLabel: 'Title',
		descriptionLabel: 'Description',
		tagsLabel: 'Tags',
		tagsHint: 'Type and press space or comma (optional)',
		massTagsHint: 'The same tags will be applied to every image',
		optionalHint: 'Optional',
		cancel: 'Cancel',
		create: 'Upload',
		creating: 'Uploading…',
		createSuccess: 'Image uploaded',
		createError: 'Could not upload the image',
		dropHint: 'Click to choose or drag files here',
		massSuccess: '{count} files were imported',
		massPartial: '{imported} of {total} files were imported',
		urlLabel: 'URL',
		urlHint: 'Paste the direct image address',
		importing: 'Importing…',
		importUrlSuccess: 'Image imported',
		isPrivate: 'Private',
		isSecret: 'Secret',
	},
	create: {
		nav: 'Create',
		back: 'Back',
		oneTitle: 'One image',
		oneSubtitle: 'from your computer/phone',
		manyTitle: 'Several images',
		manySubtitle: 'from your computer/phone',
		urlTitle: 'Import image',
		urlSubtitle: 'from an internet URL',
		pinterestTitle: 'Import folder(s)',
		pinterestSubtitle: 'from pinterest',
		uploadPageTitle: 'One image',
		massPageTitle: 'Several images',
		importUrlPageTitle: 'Import image',
		pinterestPageTitle: 'Import folder(s)',
		pinterestLinkLabel: 'Link',
		pinterestHelp:
			'Paste a Pinterest profile link to import every image from every public folder.\nOr paste a folder link to import every image saved in it.',
	},
}

export default en
