import type { AppMessages } from './types'

const passwordChecklist = {
	minLength: 'Mínimo 8 caracteres',
	complexity: 'Al menos 3 criterios de la lista abajo',
	lowercase: 'Letras minúsculas',
	uppercase: 'Letras mayúsculas',
	number: 'Números',
	symbol: 'Símbolos',
} as const

const es: AppMessages = {
	app: {
		name: 'App',
		helloWorld: 'Hello World',
		close: 'Cerrar',
	},
	nav: {
		home: 'Inicio',
		settings: 'Configuración',
		openMenu: 'Abrir menú',
		closeMenu: 'Cerrar menú',
		menu: 'Menú',
		account: 'Cuenta',
		signIn: 'Entrar',
		signUp: 'Registrarse',
		profile: 'Perfil',
		signOut: 'Salir',
		mainNavigation: 'Navegación principal',
	},
	validation: {
		required: 'Este campo es obligatorio',
		emailInvalid: 'Introduce un correo válido',
		emailRequired: 'Introduce el correo',
		passwordRequired: 'Introduce la contraseña',
		nicknameRequired: 'Introduce el nickname',
		nicknameInvalid: 'Nickname inválido tras la normalización',
		identifierRequired: 'Introduce el nickname o correo',
		urlInvalid: 'Introduce una URL válida',
		passwordConfirmationRequired: 'Confirma la contraseña',
		currentPasswordRequired: 'Introduce la contraseña actual',
		newPasswordRequired: 'Introduce la nueva contraseña',
		birthDateRequired: 'Introduce la fecha de nacimiento',
	},
	auth: {
		loginTitle: 'Entrar',
		registerTitle: 'Registrarse',
		email: 'Correo electrónico',
		identifier: 'Nickname o correo',
		password: 'Contraseña',
		passwordConfirmation: 'Confirmar contraseña',
		nickname: 'Nickname',
		birthDate: 'Fecha de nacimiento',
		birthDateHint: 'Debes tener 18 años o más.',
		mustBeAdult: 'Debes tener al menos 18 años para crear una cuenta.',
		invalidBirthDate: 'Introduce una fecha de nacimiento válida.',
		submitLogin: 'Entrar',
		submitRegister: 'Crear cuenta',
		successLogin: 'Sesión iniciada con éxito',
		successRegister: 'Cuenta creada con éxito',
		errorGeneric: 'No se pudo completar la operación',
		invalidCredentials: 'Nickname/correo o contraseña inválidos',
		nicknameTaken: 'El nickname ya está en uso',
		nicknameAvailable: 'Nickname disponible',
		nicknameUniquenessHint:
			'El nickname es único, sin distinguir mayúsculas. No se permiten caracteres visualmente iguales de otros alfabetos.',
		emailTaken: 'El correo ya está en uso',
		passwordMismatch: 'Las contraseñas no coinciden',
		passwordMinLength: 'La contraseña debe tener al menos 8 caracteres',
		passwordComplexity: 'La contraseña debe cumplir al menos 3 criterios de la lista',
		showPassword: 'Mostrar contraseña',
		hidePassword: 'Ocultar contraseña',
		passwordChecklist,
		noAccount: '¿No tienes una cuenta?',
		registerNow: 'Regístrate',
		acceptTerms: 'He leído y acepto los <terms>Términos de Uso</terms>.',
		acceptPrivacy: 'He leído y acepto la <privacy>Política de Privacidad</privacy>.',
		consentRequired: 'Acepta los términos y la política de privacidad para continuar.',
		forgotPasswordLink: 'Olvidé mi contraseña',
		forgotPasswordTitle: 'Olvidé mi contraseña',
		forgotPasswordHint:
			'Introduce tu correo. Si existe una cuenta verificada, enviaremos un código de restablecimiento.',
		forgotPasswordSubmit: 'Enviar código',
		forgotPasswordSuccess:
			'Si existe una cuenta verificada con ese correo, hemos enviado un código de restablecimiento.',
		resetPasswordTitle: 'Restablecer contraseña',
		resetPasswordSubmit: 'Actualizar contraseña',
		resetPasswordSuccess: 'Contraseña actualizada. Ya puedes iniciar sesión con la nueva contraseña.',
		resetPasswordError: 'Código inválido o caducado. Solicita un nuevo correo de restablecimiento.',
		resetCode: 'Código de restablecimiento',
		newPassword: 'Nueva contraseña',
		newPasswordConfirmation: 'Confirmar nueva contraseña',
		backToLogin: 'Volver al inicio de sesión',
		continueWithGoogle: 'Continuar con Google',
		googleLoginRequired: 'Esta cuenta usa Google. Inicia sesión con Continuar con Google.',
		googleRegisterTitle: 'Completar registro con Google',
		googleRegisterHint: 'Confirma tu edad y acepta los documentos legales para crear tu cuenta.',
		googleRegisterSubmit: 'Crear cuenta con Google',
		googleRegisterSuccess: 'Cuenta creada con Google',
		googleLinkTitle: 'Vincular cuenta de Google',
		googleLinkMessage:
			'Ya existe una cuenta App con este correo y contraseña. Introduce tu contraseña actual para vincular Google.',
		googleLinkSubmit: 'Vincular e iniciar sesión',
		googleLinkSuccess: 'Google vinculado correctamente',
		emailChangeCancelledMessage:
			'Continuar con Google cancela cualquier cambio de correo pendiente en esta cuenta.',
		googleEmailUnverifiedMessage:
			'El correo de la cuenta de Google no está verificado. Deberás verificar el correo de nuevo en App.',
	},
	legal: {
		privacyTitle: 'Política de Privacidad',
		termsTitle: 'Términos de Uso',
		privacyMetaDescription:
			'Política de privacidad de App: finalidades, bases legales, retención, transferencia internacional y derechos de la LGPD.',
		termsMetaDescription:
			'Términos de uso de App para cuenta, contenido enviado, reglas de la plataforma y colaboración con autoridades.',
		versionLabel: 'Versión {version}',
		privacyLink: 'Privacidad',
		termsLink: 'Términos',
		privacyLinkShort: 'Priv.',
		termsLinkShort: 'Térm.',
		linksLabel: 'Documentos legales',
		cookieNotice:
			'Usamos cookies esenciales de sesión, tema e idioma. No usamos rastreadores de marketing. Más detalles en la política de privacidad.',
		cookieDismiss: 'Entendido',
	},
	profile: {
		title: 'Perfil',
		name: 'Nombre completo',
		nickname: 'Nickname',
		nicknameUniquenessHint:
			'El nickname es único, sin distinguir mayúsculas. No se permiten caracteres visualmente iguales de otros alfabetos.',
		photo: 'Foto de perfil',
		photoHelper: 'JPEG, PNG, WebP o GIF hasta 3MB',
		addPhoto: 'Añadir foto de perfil',
		removePhoto: 'Quitar foto de perfil',
		changePhoto: 'Clic para cambiar',
		saveProfile: 'Guardar perfil',
		changePassword: 'Cambiar contraseña',
		currentPassword: 'Contraseña actual',
		currentPasswordGoogleHint:
			'Las cuentas de Google sin contraseña pueden dejar este campo en blanco al definir la primera contraseña.',
		newPassword: 'Nueva contraseña',
		newPasswordConfirmation: 'Confirmar nueva contraseña',
		successProfile: 'Perfil actualizado',
		successPassword: 'Contraseña actualizada',
		successPhoto: 'Foto actualizada',
		downloadMyData: 'Descargar mis datos',
		successExport: 'Exportación lista',
		deleteAccount: 'Eliminar cuenta',
		deleteAccountDescription:
			'Tu cuenta entra en cuarentena por 30 días. Los contenidos se ocultan de inmediato. Si inicias sesión en ese plazo, puedes cancelar la eliminación. Después de 30 días, los datos se borran de forma irreversible.',
		deleteAccountConfirm: 'Escribe ELIMINAR para confirmar',
		deleteAccountPassword: 'Contraseña actual para confirmar la eliminación',
		deleteAccountSubmit: 'Eliminar mi cuenta',
		successDeleteAccount: 'Eliminación solicitada — cuenta en cuarentena',
		errorDeleteAccount: 'No se pudo eliminar la cuenta',
		accountDeletion: {
			title: 'Eliminación de cuenta solicitada',
			requestedAt: 'Solicitud realizada el {datetime} (UTC) por ti.',
			deadlineAt: 'Fecha límite para cancelar y recuperar la cuenta: {datetime} (UTC).',
			bodyQuarantine:
				'Tu cuenta y tus contenidos están en cuarentena y ocultos. Pueden restaurarse si cancelas la eliminación en un plazo de 30 días.',
			bodyRestore:
				'Al iniciar sesión en esta cuenta, puedes CANCELAR la solicitud de eliminación (restaurar) o MANTENER la eliminación (permanecer en cuarentena).',
			bodyIrreversible: 'Conforme la LGPD, después del plazo los datos se eliminarán de forma IRRECUPERABLE.',
			keepButton: 'MANTENER eliminación del perfil',
			cancelButton: 'CANCELAR eliminación del perfil',
			infoOnlyHint:
				'Enviamos un correo con estos detalles. Para cancelar la eliminación, inicia sesión de nuevo dentro del plazo.',
			successCancel: 'Eliminación cancelada — cuenta restaurada',
			successKeep: 'Eliminación mantenida — la cuenta permanece en cuarentena',
			errorAction: 'No se pudo completar la acción',
			loading: 'Cargando…',
		},
		errorGeneric: 'No se pudieron guardar los cambios',
		passwordMismatch: 'Las contraseñas no coinciden',
		passwordMinLength: 'La contraseña debe tener al menos 8 caracteres',
		passwordComplexity: 'La contraseña debe cumplir al menos 3 criterios de la lista',
		showPassword: 'Mostrar contraseña',
		hidePassword: 'Ocultar contraseña',
		passwordChecklist,
		accountUnverified: 'Cuenta no verificada',
		accountVerified: 'Cuenta verificada',
		email: 'Correo electrónico',
		emailDisplay: 'Correo: {email}',
		resendVerification: 'Reenviar correo de verificación',
		verificationToken: 'Código de verificación',
		confirmVerification: 'Verificar cuenta',
		pendingEmailChange: 'Cambio pendiente a {email}',
		changeEmail: 'Cambiar correo',
		currentEmail: 'Correo actual',
		newEmail: 'Nuevo correo',
		emailChangeInboxHint: 'Revisa tu bandeja de entrada para confirmar el cambio de correo.',
		emailChangeRequiresVerified: 'Confirma tu cuenta antes de cambiar el correo.',
		emailChangeUnlinksGoogleWarning:
			'Cambiar el correo desvincula Google de esta cuenta. Tendrás que vincularlo de nuevo después si quieres.',
		emailChangeWillUnlinkGoogle: 'El vínculo con Google se eliminará al completar el cambio de correo.',
		successVerificationSent: 'Correo de verificación enviado',
		errorVerificationSent: 'No se pudo enviar el correo de verificación',
		successEmailChangeRequested: 'Correo de confirmación enviado a tu dirección actual',
		verifyEmailTitle: 'Verificar correo',
		verifyEmailSuccess: 'Tu correo se verificó correctamente.',
		verifyEmailError: 'No se pudo verificar este código de correo.',
		confirmEmailChangeTitle: 'Confirmar cambio de correo',
		confirmEmailChangeSuccess: 'Tu correo se actualizó correctamente.',
		confirmEmailChangePendingNew: 'Dirección actual confirmada. Revisa tu nuevo correo para terminar.',
		confirmEmailChangeError: 'No se pudo confirmar este enlace de cambio de correo.',
		goToProfile: 'Ir al perfil',
		activeSessions: 'Sesiones activas',
		sessionCurrent: 'Esta sesión',
		sessionRevoke: 'Revocar',
		sessionRevokeOthers: 'Revocar otras sesiones',
		sessionEmpty: 'No hay sesiones activas.',
		sessionDevice: 'Dispositivo',
		sessionCreated: 'Creada el',
		sessionExpires: 'Expira el',
		statistics: 'Estadísticas',
		statisticsFileCount: 'Archivos almacenados',
		statisticsStorageUsed: 'Espacio utilizado',
		statisticsStorageUsedValue: '{megabytes} MB',
		statisticsLoading: '…',
	},
	settings: {
		title: 'Configuración',
		general: {
			title: 'General',
			description: 'Preferencias básicas de la interfaz.',
			darkMode: 'Activar tema oscuro',
			language: 'Idioma',
		},
		languages: {
			pt: 'Portugués',
			en: 'Inglés',
			es: 'Español',
		},
	},
	notFound: {
		title: 'Página no encontrada',
		description: 'La dirección solicitada no existe o no está disponible.',
		backHome: 'Volver al inicio',
	},
	error: {
		title: 'Algo salió mal',
		description: 'No se pudo cargar esta página. Inténtalo de nuevo o vuelve al inicio.',
		retry: 'Intentar de nuevo',
		backHome: 'Volver al inicio',
	},
	apiError: {
		timeout: 'La solicitud tardó demasiado. Comprueba tu conexión e inténtalo de nuevo.',
		unauthorized: 'Tu sesión expiró o no tienes permiso. Inicia sesión de nuevo.',
		server: 'El servidor tuvo un problema. Inténtalo de nuevo en un momento.',
		network: 'No se pudo conectar. Comprueba tu internet e inténtalo de nuevo.',
		generic: 'No se pudo completar la operación.',
	},
	home: {
		title: 'Bienvenido',
		description: 'Webapp inicial con autenticación, configuración, almacenamiento de archivos y correo.',
		loading: 'Cargando…',
		signedInAs: 'Conectado como',
		guestPrompt: 'Inicia sesión o crea una cuenta para acceder a tu perfil y configuración.',
	},
	documentTitle: {
		profile: 'Mi perfil',
		settings: 'Configuración',
		dsComponents: 'Design system',
		privacy: 'Privacidad',
		terms: 'Términos',
	},
	dsCatalog: {
		title: 'Catálogo del design system',
		description:
			'Referencia interactiva de componentes compartidos. Actualiza esta página al añadir componentes en src/design-system/.',
		searchPlaceholder: 'Buscar componentes…',
		importLabel: 'Import',
		categoryLabel: 'Categoría',
		exampleLabel: 'Ejemplo',
		noResults: 'Ningún componente coincide con la búsqueda.',
		categories: {
			actions: 'Acciones',
			inputs: 'Entradas',
			navigation: 'Navegación',
			feedback: 'Feedback',
			layout: 'Layout',
			icons: 'Iconos',
		},
	},
}

export default es
