import type { AppMessages } from './types'

const passwordChecklist = {
	minLength: 'Mínimo 8 caracteres',
	complexity: 'Ao menos 3 critérios da lista abaixo',
	lowercase: 'Letras minúsculas',
	uppercase: 'Letras maiúsculas',
	number: 'Números',
	symbol: 'Símbolos',
} as const

const pt: AppMessages = {
	app: {
		name: 'App',
		helloWorld: 'Hello World',
		close: 'Fechar',
	},
	nav: {
		home: 'Início',
		images: 'Imagens',
		create: 'Criar',
		settings: 'Configurações',
		openMenu: 'Abrir menu',
		closeMenu: 'Fechar menu',
		menu: 'Menu',
		account: 'Conta',
		signIn: 'Entrar',
		signUp: 'Cadastrar',
		profile: 'Perfil',
		signOut: 'Sair',
		mainNavigation: 'Navegação principal',
	},
	validation: {
		required: 'Este campo é obrigatório',
		emailInvalid: 'Informe um e-mail válido',
		emailRequired: 'Informe o e-mail',
		passwordRequired: 'Informe a senha',
		nicknameRequired: 'Informe o nickname',
		nicknameInvalid: 'Nickname inválido após normalização',
		identifierRequired: 'Informe o nickname ou e-mail',
		urlInvalid: 'Informe uma URL válida',
		passwordConfirmationRequired: 'Confirme a senha',
		currentPasswordRequired: 'Informe a senha atual',
		newPasswordRequired: 'Informe a nova senha',
		birthDateRequired: 'Informe a data de nascimento',
	},
	auth: {
		loginTitle: 'Entrar',
		registerTitle: 'Cadastrar',
		email: 'E-mail',
		identifier: 'Nickname ou e-mail',
		password: 'Senha',
		passwordConfirmation: 'Confirmar senha',
		nickname: 'Nickname',
		birthDate: 'Data de nascimento',
		birthDateHint: 'Você precisa ter 18 anos ou mais.',
		mustBeAdult: 'Você precisa ter 18 anos para criar uma conta.',
		invalidBirthDate: 'Informe uma data de nascimento válida.',
		submitLogin: 'Entrar',
		submitRegister: 'Criar conta',
		successLogin: 'Login realizado com sucesso',
		successRegister: 'Conta criada com sucesso',
		errorGeneric: 'Não foi possível concluir a operação',
		invalidCredentials: 'Nickname/e-mail ou senha inválidos',
		nicknameTaken: 'Nickname já está em uso',
		nicknameAvailable: 'Nickname disponível',
		nicknameUniquenessHint:
			'O nickname é único, ignorando maiúsculas. Caracteres visualmente iguais de outros alfabetos não são permitidos.',
		emailTaken: 'E-mail já está em uso',
		passwordMismatch: 'As senhas não coincidem',
		passwordMinLength: 'A senha deve ter pelo menos 8 caracteres',
		passwordComplexity: 'A senha deve cumprir ao menos 3 critérios da lista',
		showPassword: 'Mostrar senha',
		hidePassword: 'Ocultar senha',
		passwordChecklist,
		noAccount: 'Não tem uma conta?',
		registerNow: 'Registre-se',
		acceptTerms: 'Li e aceito os <terms>Termos de Uso</terms>.',
		acceptPrivacy: 'Li e aceito a <privacy>Política de Privacidade</privacy>.',
		consentRequired: 'Aceite os termos e a política de privacidade para continuar.',
		forgotPasswordLink: 'Esqueci a senha',
		forgotPasswordTitle: 'Esqueci a senha',
		forgotPasswordHint: 'Informe seu e-mail. Se existir uma conta verificada, enviaremos um código de redefinição.',
		forgotPasswordSubmit: 'Enviar código',
		forgotPasswordSuccess: 'Se existir uma conta verificada com esse e-mail, enviamos um código de redefinição.',
		resetPasswordTitle: 'Redefinir senha',
		resetPasswordSubmit: 'Atualizar senha',
		resetPasswordSuccess: 'Senha atualizada. Você já pode entrar com a nova senha.',
		resetPasswordError: 'Código inválido ou expirado. Solicite um novo e-mail de redefinição.',
		resetCode: 'Código de redefinição',
		newPassword: 'Nova senha',
		newPasswordConfirmation: 'Confirmar nova senha',
		backToLogin: 'Voltar ao login',
		continueWithGoogle: 'Continuar com Google',
		googleLoginRequired: 'Esta conta usa o Google. Entre com Continuar com Google.',
		googleRegisterTitle: 'Concluir cadastro com Google',
		googleRegisterHint: 'Confirme sua idade e aceite os documentos legais para criar sua conta.',
		googleRegisterSubmit: 'Criar conta com Google',
		googleRegisterSuccess: 'Conta criada com Google',
		googleLinkTitle: 'Vincular conta Google',
		googleLinkMessage:
			'Já existe uma conta App com este e-mail e senha. Informe sua senha atual para vincular o Google.',
		googleLinkSubmit: 'Vincular e entrar',
		googleLinkSuccess: 'Google vinculado com sucesso',
		emailChangeCancelledMessage:
			'Continuar com o Google cancela qualquer alteração de e-mail pendente nesta conta.',
		googleEmailUnverifiedMessage:
			'O e-mail da conta Google não está verificado. Será necessário verificar o e-mail novamente no App.',
	},
	legal: {
		privacyTitle: 'Política de Privacidade',
		termsTitle: 'Termos de Uso',
		privacyMetaDescription:
			'Política de privacidade do App: finalidades, bases legais, retenção, transferência internacional e direitos da LGPD.',
		termsMetaDescription:
			'Termos de uso do App para conta, conteúdo enviado, regras da plataforma e colaboração com autoridades.',
		versionLabel: 'Versão {version}',
		privacyLink: 'Privacidade',
		termsLink: 'Termos',
		privacyLinkShort: 'Priv.',
		termsLinkShort: 'Termos',
		linksLabel: 'Documentos legais',
		cookieNotice:
			'Usamos cookies essenciais de sessão, tema e idioma. Não usamos rastreadores de marketing. Detalhes na política de privacidade.',
		cookieDismiss: 'Entendi',
	},
	profile: {
		title: 'Perfil',
		name: 'Nome completo',
		nickname: 'Nickname',
		nicknameUniquenessHint:
			'O nickname é único, ignorando maiúsculas. Caracteres visualmente iguais de outros alfabetos não são permitidos.',
		photo: 'Foto de perfil',
		photoHelper: 'JPEG, PNG, WebP ou GIF até 3MB',
		addPhoto: 'Adicionar foto de perfil',
		removePhoto: 'Remover foto de perfil',
		changePhoto: 'Clique para alterar',
		saveProfile: 'Salvar perfil',
		changePassword: 'Alterar senha',
		currentPassword: 'Senha atual',
		currentPasswordGoogleHint:
			'Contas Google sem senha podem deixar este campo em branco ao definir a primeira senha.',
		newPassword: 'Nova senha',
		newPasswordConfirmation: 'Confirmar nova senha',
		successProfile: 'Perfil atualizado',
		successPassword: 'Senha atualizada',
		successPhoto: 'Foto atualizada',
		downloadMyData: 'Baixar meus dados',
		successExport: 'Exportação pronta',
		deleteAccount: 'Excluir conta',
		deleteAccountDescription:
			'Sua conta entra em quarentena por 30 dias. Conteúdos ficam ocultos de imediato. Se você fizer login nesse período, poderá cancelar a exclusão. Após 30 dias, os dados serão apagados de forma irrecuperável.',
		deleteAccountConfirm: 'Digite EXCLUIR para confirmar',
		deleteAccountPassword: 'Senha atual para confirmar a exclusão',
		deleteAccountSubmit: 'Excluir minha conta',
		successDeleteAccount: 'Exclusão solicitada — conta em quarentena',
		errorDeleteAccount: 'Não foi possível excluir a conta',
		accountDeletion: {
			title: 'Exclusão de conta solicitada',
			requestedAt: 'Solicitação feita em {datetime} (UTC) por você.',
			deadlineAt: 'Data limite para cancelar e recuperar a conta: {datetime} (UTC).',
			bodyQuarantine:
				'Sua conta e seus conteúdos estão em quarentena e ocultos. Eles podem ser restaurados se você cancelar a exclusão dentro de 30 dias.',
			bodyRestore:
				'Ao fazer login nesta conta, você pode CANCELAR a solicitação de exclusão (restaurar) ou MANTER a exclusão (permanecer em quarentena).',
			bodyIrreversible: 'Conforme a LGPD, após o prazo os dados serão excluídos de maneira IRRECUPERÁVEL.',
			keepButton: 'MANTER exclusão do perfil',
			cancelButton: 'CANCELAR exclusão do perfil',
			infoOnlyHint:
				'Enviamos um e-mail com estes detalhes. Para cancelar a exclusão, faça login novamente dentro do prazo.',
			successCancel: 'Exclusão cancelada — conta restaurada',
			successKeep: 'Exclusão mantida — conta permanece em quarentena',
			errorAction: 'Não foi possível concluir a ação',
			loading: 'Carregando…',
		},
		errorGeneric: 'Não foi possível salvar as alterações',
		passwordMismatch: 'As senhas não coincidem',
		passwordMinLength: 'A senha deve ter pelo menos 8 caracteres',
		passwordComplexity: 'A senha deve cumprir ao menos 3 critérios da lista',
		showPassword: 'Mostrar senha',
		hidePassword: 'Ocultar senha',
		passwordChecklist,
		accountUnverified: 'Conta não verificada',
		accountVerified: 'Conta verificada',
		email: 'E-mail',
		emailDisplay: 'E-mail: {email}',
		resendVerification: 'Reenviar e-mail de verificação',
		verificationToken: 'Código de verificação',
		confirmVerification: 'Verificar conta',
		pendingEmailChange: 'Alteração pendente para {email}',
		changeEmail: 'Alterar e-mail',
		currentEmail: 'E-mail atual',
		newEmail: 'Novo e-mail',
		emailChangeInboxHint: 'Verifique sua caixa de entrada para confirmar a alteração de e-mail.',
		emailChangeRequiresVerified: 'Confirme sua conta antes de alterar o e-mail.',
		emailChangeUnlinksGoogleWarning:
			'Alterar o e-mail desvincula o Google desta conta. Você precisará vincular de novo depois, se quiser.',
		emailChangeWillUnlinkGoogle: 'O vínculo com o Google será removido ao concluir a troca de e-mail.',
		successVerificationSent: 'E-mail de verificação enviado',
		errorVerificationSent: 'Não foi possível enviar o e-mail de verificação',
		successEmailChangeRequested: 'E-mail de confirmação enviado para o endereço atual',
		verifyEmailTitle: 'Verificar e-mail',
		verifyEmailSuccess: 'Seu e-mail foi verificado com sucesso.',
		verifyEmailError: 'Não foi possível verificar este código de e-mail.',
		confirmEmailChangeTitle: 'Confirmar alteração de e-mail',
		confirmEmailChangeSuccess: 'Seu e-mail foi atualizado com sucesso.',
		confirmEmailChangePendingNew: 'Endereço atual confirmado. Confira a nova caixa de entrada para concluir.',
		confirmEmailChangeError: 'Não foi possível confirmar este link de alteração de e-mail.',
		goToProfile: 'Ir para o perfil',
		activeSessions: 'Sessões ativas',
		sessionCurrent: 'Esta sessão',
		sessionRevoke: 'Revogar',
		sessionRevokeOthers: 'Revogar outras sessões',
		sessionEmpty: 'Nenhuma sessão ativa.',
		sessionDevice: 'Dispositivo',
		sessionCreated: 'Criada em',
		sessionExpires: 'Expira em',
		statistics: 'Estatísticas',
		statisticsImageCount: 'Quantidade de imagens',
		statisticsStorageUsed: 'Espaço utilizado',
		statisticsStorageUsedValue: '{megabytes} MB',
	},
	settings: {
		title: 'Configurações',
		general: {
			title: 'Geral',
			description: 'Preferências básicas da interface.',
			darkMode: 'Ativar tema escuro',
			language: 'Idioma',
			showSecretImages: 'Exibir imagens SECRET',
			showSecretImagesDescription:
				'Mostra suas imagens SECRET em Minhas imagens e permite marcá-las como SECRET.',
			appearInGlobalMosaic: 'Aparecer no mosaico global',
			appearInGlobalMosaicDescription: 'Se desligado, suas imagens públicas não entram no feed da home.',
		},
		languages: {
			pt: 'Português',
			en: 'Inglês',
			es: 'Espanhol',
		},
	},
	notFound: {
		title: 'Página não encontrada',
		description: 'O endereço solicitado não existe ou não está disponível.',
		backHome: 'Voltar ao início',
	},
	error: {
		title: 'Algo deu errado',
		description: 'Não foi possível carregar esta página. Tente novamente ou volte ao início.',
		retry: 'Tentar novamente',
		backHome: 'Voltar ao início',
	},
	apiError: {
		timeout: 'A solicitação demorou demais. Verifique sua conexão e tente de novo.',
		unauthorized: 'Sua sessão expirou ou você não tem permissão. Entre novamente.',
		server: 'O servidor encontrou um problema. Tente novamente em instantes.',
		network: 'Não foi possível conectar. Verifique sua internet e tente de novo.',
		generic: 'Não foi possível concluir a operação.',
	},
	mosaic: {
		close: 'Fechar',
		closeWithoutSaving: 'Fechar sem salvar',
		delete: 'Excluir',
		deleteConfirm: 'Clique de novo para excluir',
		deleting: 'Excluindo…',
		deleteError: 'Não foi possível excluir a imagem',
		deleteSuccess: 'Imagem excluída',
		save: 'Salvar',
		saving: 'Salvando…',
		saveError: 'Não foi possível salvar a imagem',
		saveSuccess: 'Imagem salva',
		isPrivate: 'Privada',
		isSecret: 'Secret',
		showText: 'Mostrar texto',
		showImage: 'Mostrar imagem',
		zoomLabel: 'Zoom do board',
		zoomColumns: '{count} colunas',
		imageMissing: 'Essa imagem não existe ou foi excluída',
		untitled: 'Imagem',
		imageDetails: 'Detalhes da imagem',
		openImage: 'Abrir imagem',
		empty: 'Ainda não há imagens.',
		loadMore: 'Carregar mais',
	},
	report: {
		button: 'Reportar',
		title: 'Reportar imagem',
		description: 'Descreva o problema. Nossa equipe revisará a denúncia.',
		reason: 'Motivo',
		reasonPlaceholder: 'Selecione um motivo',
		details: 'Detalhes (opcional)',
		detailsHint: 'Não inclua dados sensíveis desnecessários.',
		submit: 'Enviar denúncia',
		cancel: 'Cancelar',
		success: 'Denúncia enviada',
		errorGeneric: 'Não foi possível enviar a denúncia',
		alreadyReported: 'Você já reportou esta imagem',
		loginRequired: 'Entre na conta para reportar',
		reasons: {
			spam: 'Spam',
			nudes_nonconsensual: 'Nudes sem consentimento',
			csam: 'Abuso sexual infantil (CSAM)',
			impersonation: 'Personificação / falsidade',
			other: 'Outro',
		},
	},
	home: {
		title: 'Bem-vindo',
		description: 'Webapp inicial com autenticação, configurações, armazenamento de arquivos e e-mail.',
		loading: 'Carregando…',
		signedInAs: 'Conectado como',
		guestPrompt: 'Entre ou crie uma conta para acessar seu perfil e configurações.',
	},
	documentTitle: {
		images: 'Minhas imagens',
		create: 'Nova imagem',
		profile: 'Meu perfil',
		settings: 'Configurações',
		imageUpload: 'Nova imagem',
		imageMassUpload: 'Upload em massa',
		imageImportUrl: 'Importar URL',
		imageImportPinterest: 'Importar do Pinterest',
		privacy: 'Privacidade',
		terms: 'Termos',
	},
	images: {
		pageTitle: 'Minhas imagens',
		searchLabel: 'Buscar imagens',
		searchPlaceholder: 'Buscar por título ou descrição',
		noTagsYet: 'Nenhuma tag cadastrada ainda',
		empty: 'Você ainda não cadastrou imagens.',
		emptyFiltered: 'Você não cadastrou imagens nesses critérios de busca',
		loading: 'Carregando…',
		loadError: 'Não foi possível carregar as imagens',
		loadMore: 'Carregar mais',
		createFab: 'Cadastrar imagem',
		createTitle: 'Nova imagem',
		fileLabel: 'Arquivo',
		fileHint: 'JPEG, PNG, WebP ou GIF até 3MB',
		fileReadError: 'Não foi possível ler o arquivo',
		titleLabel: 'Título',
		descriptionLabel: 'Descrição',
		tagsLabel: 'Tags',
		tagsHint: 'Digite e pressione espaço ou vírgula (opcional)',
		massTagsHint: 'As mesmas tags serão aplicadas a todas as imagens',
		optionalHint: 'Opcional',
		cancel: 'Cancelar',
		create: 'Cadastrar',
		creating: 'Cadastrando…',
		createSuccess: 'Imagem cadastrada',
		createError: 'Não foi possível cadastrar a imagem',
		dropHint: 'Clique para escolher ou arraste arquivos para cá',
		massSuccess: '{count} arquivos foram importados',
		massPartial: '{imported} de {total} arquivos foram importados',
		urlLabel: 'URL',
		urlHint: 'Cole o endereço direto da imagem',
		importing: 'Importando…',
		importUrlSuccess: 'Imagem importada',
		isPrivate: 'Privada',
		isSecret: 'Secret',
	},
	create: {
		nav: 'Criar',
		back: 'Voltar',
		oneTitle: 'Uma imagem',
		oneSubtitle: 'do seu pc/celular',
		manyTitle: 'Várias imagens',
		manySubtitle: 'do seu pc/celular',
		urlTitle: 'Importar imagem',
		urlSubtitle: 'de uma url da internet',
		pinterestTitle: 'Importar pasta(s)',
		pinterestSubtitle: 'do pinterest',
		uploadPageTitle: 'Uma imagem',
		massPageTitle: 'Várias imagens',
		importUrlPageTitle: 'Importar imagem',
		pinterestPageTitle: 'Importar pasta(s)',
		pinterestLinkLabel: 'Link',
		pinterestHelp:
			'Cole aqui um link de perfil do pinterest para importar todas as imagens de todas as pastas públicas.\nOu então, cole o link de uma pasta para importar todas as imagens salvas nela.',
	},
}

export default pt
