export type DsCatalogCategory = 'actions' | 'inputs' | 'navigation' | 'feedback' | 'layout' | 'icons'

export type DsCatalogEntry = {
	id: string
	name: string
	category: DsCatalogCategory
	description: string
	importLine: string
	keywords: string[]
}

/** Single source of truth for the /ds-components page. Keep in sync with src/design-system/index.ts. */
export const DS_CATALOG: DsCatalogEntry[] = [
	{
		id: 'Button',
		name: 'Button',
		category: 'actions',
		description: 'Primary action control. Wraps the shadcn Button with app defaults.',
		importLine: "import { Button } from '@/design-system'",
		keywords: ['submit', 'click', 'cta'],
	},
	{
		id: 'ConfirmActionButton',
		name: 'ConfirmActionButton',
		category: 'actions',
		description: 'Two-step confirmation button. First click arms; second click runs onConfirm.',
		importLine: "import { ConfirmActionButton } from '@/design-system'",
		keywords: ['delete', 'destructive', 'confirm'],
	},
	{
		id: 'ComplexButton',
		name: 'ComplexButton',
		category: 'actions',
		description: 'Large tile with icon, title and subtitle. Works as button or Link.',
		importLine: "import { ComplexButton } from '@/design-system'",
		keywords: ['tile', 'card', 'navigation'],
	},
	{
		id: 'Toggle',
		name: 'Toggle',
		category: 'inputs',
		description: 'Boolean switch for settings such as dark mode.',
		importLine: "import { Toggle } from '@/design-system'",
		keywords: ['switch', 'boolean', 'settings'],
	},
	{
		id: 'AppSlider',
		name: 'AppSlider',
		category: 'inputs',
		description: 'Numeric range input with label support for preference screens.',
		importLine: "import { AppSlider } from '@/design-system'",
		keywords: ['range', 'zoom', 'number'],
	},
	{
		id: 'AppSelect',
		name: 'AppSelect',
		category: 'inputs',
		description: 'Dropdown select with value/label options and accessible labeling.',
		importLine: "import { AppSelect } from '@/design-system'",
		keywords: ['dropdown', 'language', 'options'],
	},
	{
		id: 'TextInput',
		name: 'TextInput',
		category: 'inputs',
		description: 'Single-line text field with optional label and error message.',
		importLine: "import { TextInput } from '@/design-system'",
		keywords: ['text', 'email', 'form'],
	},
	{
		id: 'TextArea',
		name: 'TextArea',
		category: 'inputs',
		description: 'Multi-line text field with optional label and error message.',
		importLine: "import { TextArea } from '@/design-system'",
		keywords: ['textarea', 'description', 'form'],
	},
	{
		id: 'InputPassword',
		name: 'InputPassword',
		category: 'inputs',
		description: 'Password field with show/hide toggle and checklist integration.',
		importLine: "import { InputPassword } from '@/design-system'",
		keywords: ['password', 'auth', 'secret'],
	},
	{
		id: 'InputTitle',
		name: 'InputTitle',
		category: 'inputs',
		description: 'Compact title input styled for inline editing contexts.',
		importLine: "import { InputTitle } from '@/design-system'",
		keywords: ['title', 'heading', 'inline'],
	},
	{
		id: 'InputTextArea',
		name: 'InputTextArea',
		category: 'inputs',
		description: 'Compact textarea styled for inline editing contexts.',
		importLine: "import { InputTextArea } from '@/design-system'",
		keywords: ['description', 'inline', 'textarea'],
	},
	{
		id: 'TagsInput',
		name: 'TagsInput',
		category: 'inputs',
		description: 'Tokenized tag entry with keyboard separators (space/comma).',
		importLine: "import { TagsInput } from '@/design-system'",
		keywords: ['tags', 'chips', 'tokens'],
	},
	{
		id: 'FileInput',
		name: 'FileInput',
		category: 'inputs',
		description: 'Native file picker button with label and hint text.',
		importLine: "import { FileInput } from '@/design-system'",
		keywords: ['upload', 'file', 'avatar'],
	},
	{
		id: 'FileDropzone',
		name: 'FileDropzone',
		category: 'inputs',
		description: 'Drag-and-drop zone for one or many files with validation hooks.',
		importLine: "import { FileDropzone } from '@/design-system'",
		keywords: ['drag', 'drop', 'upload'],
	},
	{
		id: 'SearchBar',
		name: 'SearchBar',
		category: 'inputs',
		description: 'Search field with icon and controlled value/onChange.',
		importLine: "import { SearchBar } from '@/design-system'",
		keywords: ['filter', 'query', 'search'],
	},
	{
		id: 'CodeInput',
		name: 'CodeInput',
		category: 'inputs',
		description: 'OTP-style segmented input for email verification codes.',
		importLine: "import { CodeInput } from '@/design-system'",
		keywords: ['otp', 'token', 'verification'],
	},
	{
		id: 'PasswordChecklist',
		name: 'PasswordChecklist',
		category: 'feedback',
		description: 'Live checklist of password strength rules during registration.',
		importLine: "import { PasswordChecklist } from '@/design-system'",
		keywords: ['password', 'validation', 'rules'],
	},
	{
		id: 'Icon',
		name: 'Icon',
		category: 'icons',
		description: 'Consistent Lucide icon wrapper with default sizing.',
		importLine: "import { Icon } from '@/design-system'",
		keywords: ['lucide', 'svg', 'glyph'],
	},
	{
		id: 'IconButton',
		name: 'IconButton',
		category: 'actions',
		description: 'Square icon-only button with accessible label.',
		importLine: "import { IconButton } from '@/design-system'",
		keywords: ['icon', 'toolbar'],
	},
	{
		id: 'NavIconButton',
		name: 'NavIconButton',
		category: 'navigation',
		description: 'Sidebar-sized icon button with tooltip label.',
		importLine: "import { NavIconButton } from '@/design-system'",
		keywords: ['sidebar', 'nav', 'tooltip'],
	},
	{
		id: 'NavIconLink',
		name: 'NavIconLink',
		category: 'navigation',
		description: 'Sidebar nav item wrapping a Link with tooltip. Supports asChild.',
		importLine: "import { NavIconLink } from '@/design-system'",
		keywords: ['sidebar', 'link', 'active'],
	},
	{
		id: 'GoogleIcon',
		name: 'GoogleIcon',
		category: 'icons',
		description: 'Google brand mark sized like Lucide icons for OAuth buttons.',
		importLine: "import { GoogleIcon } from '@/design-system'",
		keywords: ['oauth', 'google', 'brand'],
	},
	{
		id: 'Avatar',
		name: 'Avatar',
		category: 'layout',
		description: 'User photo with fallback slot when src is missing or fails.',
		importLine: "import { Avatar } from '@/design-system'",
		keywords: ['photo', 'profile', 'user'],
	},
	{
		id: 'Title',
		name: 'Title',
		category: 'layout',
		description: 'Page/section heading with consistent typography scale.',
		importLine: "import { Title } from '@/design-system'",
		keywords: ['heading', 'h1', 'typography'],
	},
	{
		id: 'SettingsSection',
		name: 'SettingsSection',
		category: 'layout',
		description: 'Grouped settings block with title, description and children.',
		importLine: "import { SettingsSection } from '@/design-system'",
		keywords: ['settings', 'section', 'group'],
	},
	{
		id: 'AccordionSection',
		name: 'AccordionSection',
		category: 'layout',
		description: 'Single collapsible panel. Use AccordionGroup as the parent container.',
		importLine: "import { AccordionGroup, AccordionSection } from '@/design-system'",
		keywords: ['collapse', 'profile', 'expand'],
	},
	{
		id: 'Tooltip',
		name: 'Tooltip',
		category: 'feedback',
		description: 'Hover/focus tooltip primitives. Wrap the tree with TooltipProvider.',
		importLine: "import { Tooltip, TooltipContent, TooltipProvider, TooltipTrigger } from '@/design-system'",
		keywords: ['hint', 'hover', 'label'],
	},
	{
		id: 'Toast',
		name: 'Toast',
		category: 'feedback',
		description: 'Transient notifications. Mount ToastProvider and call useToast().toast().',
		importLine: "import { Toast, ToastProvider, useToast } from '@/design-system'",
		keywords: ['notification', 'success', 'error'],
	},
	{
		id: 'AppDropdownMenu',
		name: 'AppDropdownMenu',
		category: 'navigation',
		description: 'Account/menu dropdown with items, separators and destructive actions.',
		importLine: "import { AppDropdownMenu } from '@/design-system'",
		keywords: ['menu', 'dropdown', 'account'],
	},
]

export const DS_CATALOG_BY_ID = Object.fromEntries(DS_CATALOG.map((entry) => [entry.id, entry])) as Record<
	string,
	DsCatalogEntry
>
